export const INVALID_CITY = 'INVALID_CITY';
export const RECEIVE_WEATHER = 'RECEIVE_WEATHER';
export const RECEIVE_WEATHER_FORECASTS = 'RECEIVE_WEATHER_FORECASTS';
export const BEGIN_AJAX_REQUEST = 'BEGIN_AJAX_REQUEST';
export const END_AJAX_REQUEST = 'END_AJAX_REQUEST';