export const INVALID_CITY = 'INVALID_CITY';
export const RECEIVE_WEATHER = 'RECEIVE_WEATHER';
export const RECEIVE_FORECAST = 'RECEIVE_FORECAST';
export const BEGIN_AJAX_REQUEST = 'BEGIN_AJAX_REQUEST';
export const END_AJAX_REQUEST = 'END_AJAX_REQUEST';