export const SEARCH_CITY = 'SEARCH_CITY';
export const INVALID_CITY = 'INVALID_CITY';
export const RECEIVE_CURRENT_WEATHER = 'RECEIVE_CURRENT_WEATHER';
export const RECEIVE_WEATHER_FORECAST = 'RECEIVE_WEATHER_FORECAST';